### ISSUE TITLE
It seems that the socks-server function can't be used to access the https enabled website.

### ISSUE THREAD

**Issue by hongyi-zhao** [stardiviner/proxy-mode#3]
Hi,

I tried the following settings in my `.emacs` config file:

```
(setq url-gateway-method 'socks)
(setq socks-server '("Default server" "127.0.0.1" 18888 5))
```
But when I use eww to browser websites, it seems that the HTTPS enabled website can't be opened by this method, say, for https://www.google.com. Any hints for this problem?

Regards,
HY

**Comment by stardiviner** [comment]
`url-gateway-method 'socks` 只支持 HTTP，不支持 HTTPS。

**Comment by hongyi-zhao** [comment]
Nowadays, most of the websites are based on HTTPS. Don't support HTTPS will make it useless nearly.

**Comment by stardiviner** [comment]
This is Emacs built-in support issue. I suggest you propose in Emacs-devel mailing list.

**Comment by hongyi-zhao** [comment]
I've posted this issue some time before, but there is no response on it at all.

**Comment by stardiviner** [comment]
Maybe the post is not arrived? Maybe you can try to email contact `url.el` author or maintainer.

**Comment by hongyi-zhao** [comment]
Thanks for your suggestion. I've dropped an email to Bill Perry <wmperry@gnu.org>

**Comment by stardiviner** [comment]
You're welcome. I close this issue now.
